// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMojvKJ0AWGdsR0bw5v9rXcj2MEFpuVE',
    appId: '1:864429547487:web:fd4e8c310003e89d012e6a',
    messagingSenderId: '864429547487',
    projectId: 'weather-travel-app-munshif',
    authDomain: 'weather-travel-app-munshif.firebaseapp.com',
    storageBucket: 'weather-travel-app-munshif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgeFGS5PxPuSTzBwIGhRdCF7x7HX8_zyc',
    appId: '1:864429547487:android:f5c5a7cbdb41763c012e6a',
    messagingSenderId: '864429547487',
    projectId: 'weather-travel-app-munshif',
    storageBucket: 'weather-travel-app-munshif.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw8usujFb2Cpf8ighWzE14is9houTKTLw',
    appId: '1:864429547487:ios:c772ef374b948ff6012e6a',
    messagingSenderId: '864429547487',
    projectId: 'weather-travel-app-munshif',
    storageBucket: 'weather-travel-app-munshif.firebasestorage.app',
    iosBundleId: 'com.example.weatherTravelApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw8usujFb2Cpf8ighWzE14is9houTKTLw',
    appId: '1:864429547487:ios:c772ef374b948ff6012e6a',
    messagingSenderId: '864429547487',
    projectId: 'weather-travel-app-munshif',
    storageBucket: 'weather-travel-app-munshif.firebasestorage.app',
    iosBundleId: 'com.example.weatherTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMojvKJ0AWGdsR0bw5v9rXcj2MEFpuVE',
    appId: '1:864429547487:web:aa95a43d47ff089f012e6a',
    messagingSenderId: '864429547487',
    projectId: 'weather-travel-app-munshif',
    authDomain: 'weather-travel-app-munshif.firebaseapp.com',
    storageBucket: 'weather-travel-app-munshif.firebasestorage.app',
  );
}
